/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.csye6200;

import edu.neu.csye6200.controller.ControllerStudent;
import edu.neu.csye6200.controller.ControllerTeacher;
import edu.neu.csye6200.controller.VaccineController;
import edu.neu.csye6200.model.ClassroomClass;
import edu.neu.csye6200.service.classroomFactory;
import java.util.Arrays;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;


@Component
public class ClassesjPanel extends javax.swing.JPanel {

    /**
     * Creates new form StudentsjPanel
     */
    
    @Autowired
    ControllerTeacher teachController;
    @Autowired
    ControllerStudent studentController;
    @Autowired
    VaccineController vaccineController;
    @Autowired
    classroomFactory clsroomFactory;
    
    public ClassesjPanel() {
        initComponents();
        populateClassesInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbClassroom = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 102, 102));
        setPreferredSize(new java.awt.Dimension(800, 720));

        jLabel3.setBackground(new java.awt.Color(153, 255, 153));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        tbClassroom.setBackground(new java.awt.Color(236, 235, 235));
        tbClassroom.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tbClassroom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Class_Id", "Student_Age_Group", "Teacher_List", "Student_List"
            }
        ));
        jScrollPane4.setViewportView(tbClassroom);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel3)
                .addGap(41, 41, 41)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void populateClassesInfo(){
        List<ClassroomClass> clsrooms = clsroomFactory.readAllClassRooms();
            DefaultTableModel model = (DefaultTableModel) tbClassroom.getModel();
            model.setRowCount(0);
            //if (model.getRowCount() == 0) {
            clsrooms.forEach(t -> {
                            model.addRow(new Object[]{t.getClassId(), t.getMin_age()+"-"+t.getMax_age(), Arrays.toString(t.getTeacherIdList().toArray()), Arrays.toString(t.getStudentIdList().toArray())});
                        });
            //}
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tbClassroom;
    // End of variables declaration//GEN-END:variables
}
