/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.csye6200;

import edu.neu.csye6200.controller.ControllerStudent;
import edu.neu.csye6200.controller.ControllerTeacher;
import edu.neu.csye6200.controller.VaccineController;
import edu.neu.csye6200.model.ClassroomClass;
import edu.neu.csye6200.model.StudentClass;
import edu.neu.csye6200.service.classroomFactory;
import java.net.PasswordAuthentication;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Properties;
import javax.annotation.PostConstruct;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.websocket.Session;
import org.aspectj.bridge.Message;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import javax.swing.JOptionPane;


@Component
public class StudentsjPanel extends javax.swing.JPanel {

    /**
     * Creates new form StudentsjPanel
     */
    
    @Autowired
    ControllerTeacher teachController;
    @Autowired
    ControllerStudent studentController;
    @Autowired
    VaccineController vaccineController;
    @Autowired
    classroomFactory clsroomFactory;

    
    public StudentsjPanel() {
        initComponents();
    }

    @PostConstruct
    public void init() {
        try {
            populateStudent();
        } catch (Exception c) {
            c.printStackTrace();
            System.out.println("Something Went Wrong!");
        }
    }
    public void populateStudent() {

      //studentController.removeStudents();

        List<StudentClass> students = studentController.getStudents();

        if (students.size() == 0) {
            studentController.addTestData();
            // add students to classes

            List<StudentClass> newStudents = studentController.getStudents();
            addCR(newStudents);

        } else {
            addCR(students);
            DefaultTableModel model = (DefaultTableModel) tbStudents.getModel();

            if (model.getRowCount() == 0) {
                students.forEach(t -> {
                    model.addRow(new Object[]{t.getPersonId(), t.getPersonName(), t.getPersonAge(), t.getStuParentName(), t.getStuPhoneNumber(), t.getStuRegistrationDate()});
//                      ClassroomClass classRoom = classroomFactory.getClassRoom(t.getAge());
//                classRoom.addStudentId(t.getId());
                });
            }

        }
    }

    private void addCR(List<StudentClass> newStudents) {
        newStudents.forEach(s -> {
            ClassroomClass classRoom = clsroomFactory.readClassRoom(s.getPersonAge());
            List<Integer>exStudents=classRoom.getStudentIdList();
            if(!exStudents.contains(s.getPersonId())) {
                classRoom.addStudentId(s.getPersonId());
            }

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtStudentID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtStudentName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtStudentAge = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtStudentParentName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtStudentDate = new javax.swing.JTextField();
        btnAddStu = new javax.swing.JButton();
        btnClearStu = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtStudentParentContact = new javax.swing.JTextField();
        btnDeleteStu = new javax.swing.JButton();
        btnRenewal1 = new java.awt.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbStudents = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(0, 102, 102));
        setBorder(new javax.swing.border.MatteBorder(null));
        setPreferredSize(new java.awt.Dimension(1000, 800));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "New Student", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(0, 51, 102));
        jPanel3.setOpaque(false);

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Student Id");

        txtStudentID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtStudentID.setToolTipText("");
        txtStudentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentIDActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(0, 153, 255));
        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Student Name");

        txtStudentName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtStudentName.setToolTipText("");
        txtStudentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentNameActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Age");

        txtStudentAge.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtStudentAge.setToolTipText("");
        txtStudentAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentAgeActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Parent Name");

        txtStudentParentName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtStudentParentName.setToolTipText("");
        txtStudentParentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentParentNameActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Parent Contact");

        txtStudentDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtStudentDate.setToolTipText("");
        txtStudentDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentDateActionPerformed(evt);
            }
        });

        btnAddStu.setBackground(new java.awt.Color(204, 255, 204));
        btnAddStu.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAddStu.setText("Add Student");
        btnAddStu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStuActionPerformed(evt);
            }
        });

        btnClearStu.setBackground(new java.awt.Color(204, 255, 204));
        btnClearStu.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnClearStu.setText("Clear");
        btnClearStu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearStuActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Registration Date");

        txtStudentParentContact.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtStudentParentContact.setToolTipText("");
        txtStudentParentContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentParentContactActionPerformed(evt);
            }
        });

        btnDeleteStu.setBackground(new java.awt.Color(204, 255, 204));
        btnDeleteStu.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnDeleteStu.setText("Delete");
        btnDeleteStu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteStuActionPerformed(evt);
            }
        });

        btnRenewal1.setBackground(new java.awt.Color(51, 204, 0));
        btnRenewal1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnRenewal1.setForeground(new java.awt.Color(0, 0, 0));
        btnRenewal1.setLabel("Renew");
        btnRenewal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRenewal1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAddStu, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteStu, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtStudentParentName)
                    .addComponent(txtStudentName)
                    .addComponent(txtStudentID)
                    .addComponent(txtStudentAge, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtStudentDate)
                    .addComponent(txtStudentParentContact, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnClearStu, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(btnRenewal1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStudentAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtStudentParentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtStudentParentContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtStudentDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAddStu, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnClearStu, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDeleteStu, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnRenewal1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbStudents.setBackground(new java.awt.Color(235, 235, 235));
        tbStudents.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tbStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student_Id", "Student_Name", "Student_Age", "Parent_Name", "Parent_Contact", "Reg_Date"
            }
        ));
        jScrollPane1.setViewportView(tbStudents);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stu1.jpeg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(271, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(182, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtStudentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentIDActionPerformed

    private void txtStudentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentNameActionPerformed

    private void txtStudentAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentAgeActionPerformed

    private void txtStudentParentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentParentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentParentNameActionPerformed

    private void txtStudentDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentDateActionPerformed

    private void btnAddStuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStuActionPerformed
        // TODO add your handling code here:
        String id = txtStudentID.getText();
        String age = txtStudentAge.getText();
        String name = txtStudentName.getText();
        String parentName = txtStudentParentName.getText();
        String parentContact = txtStudentParentContact.getText();
        String rd = txtStudentDate.getText();

        ClassroomClass classRoom = clsroomFactory.readClassRoom(Integer.parseInt(age));
        System.out.print("classr room id is : " + classRoom.getClassId());

        int studentCount = classRoom.getStudentIdList().size();
        int teacherCount = classRoom.getTeacherIdList().size();

        float ratio = (float)studentCount / (float)teacherCount;
        System.out.println("counts in class beofr addition : "+ studentCount + " : "+ teacherCount);
        System.out.println("current ration of class will be : "+ ratio + " .Ideal : "+ classRoom.getGroupsize());

        if (ratio >= classRoom.getGroupsize()) {
            JOptionPane.showMessageDialog(this, "ClassRoom Limit is Reached", "Increase Teacher Count", JOptionPane.ERROR_MESSAGE);
        } else { 

            if (id.isEmpty() || age.isEmpty() || name.isEmpty() || parentName.isEmpty() || parentContact.isEmpty() || rd.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please Enter All Fields", "Try Again", JOptionPane.ERROR_MESSAGE);
            } else {
                DefaultTableModel model = (DefaultTableModel) tbStudents.getModel();
                model.addRow(new Object[]{id, name, age, parentName, parentContact, rd});
            }

            txtStudentID.setText("");
            txtStudentAge.setText("");
            txtStudentName.setText("");
            txtStudentParentName.setText("");
            txtStudentParentContact.setText("");
            txtStudentDate.setText("");

            String grade = "4";
            String addr = "Boston";
            String email = "kid@neu.edu";
            String csv = id + "," + name + "," + age + "," + grade + "," + rd + "," + parentName + "," + addr + "," + parentContact + "," + email;
            System.err.println(csv + "is added to student db");

            studentController.addStudent(csv);

            classRoom.addStudentId(Integer.parseInt(id));

            clsroomFactory.diplayAllClassrooms();

        }
    }//GEN-LAST:event_btnAddStuActionPerformed

    private void btnClearStuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearStuActionPerformed
        // TODO add your handling code here:
        txtStudentID.setText("");
        txtStudentAge.setText("");
        txtStudentName.setText("");
        txtStudentParentName.setText("");
        txtStudentParentContact.setText("");
        txtStudentDate.setText("");
    }//GEN-LAST:event_btnClearStuActionPerformed

    private void txtStudentParentContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentParentContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentParentContactActionPerformed

    private void btnDeleteStuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteStuActionPerformed
        // TODO add your handling code here:
//        int row = tableStudents.getSelectedRow();
//
//        if (row < 0 ) {
//            JOptionPane.showMessageDialog(this, "No Row is Selected", "Please Select Row", JOptionPane.ERROR_MESSAGE);
//        } else {
//            DefaultTableModel model = (DefaultTableModel)tableStudents.getModel();
//            model.removeRow(row);
//        }

        int row = tbStudents.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "No Row is Selected", "Please Select Row", JOptionPane.ERROR_MESSAGE);
        } else {
            //int pkid = (int)tableTeachers.getModel().getValueAt(row, 0);
            DefaultTableModel model = (DefaultTableModel) tbStudents.getModel();
//            String k = model.getValueAt(0, 0).toString();
//            System.err.println(k + " is about to deleted : " + row);

            int pkid = Integer.parseInt(model.getValueAt(row, 0).toString());
            model.removeRow(row);

            System.err.println(pkid + " is deleted : " + row);
            int age = studentController.readStudentById(pkid).get().getPersonAge();
            studentController.removeStudentById(pkid);

            ClassroomClass classRoom = clsroomFactory.readClassRoom(age);
            classRoom.deleteStudentId(pkid);
        }
    }//GEN-LAST:event_btnDeleteStuActionPerformed

    private void btnRenewal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRenewal1ActionPerformed
        // TODO add your handling code here:
        int row = tbStudents.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "No Row is Selected", "Please Select Row", JOptionPane.ERROR_MESSAGE);
        } else {
            //int pkid = (int)tableTeachers.getModel().getValueAt(row, 0);
            DefaultTableModel model = (DefaultTableModel) tbStudents.getModel();
//            String k = model.getValueAt(0, 0).toString();
//            System.err.println(k + " is about to deleted : " + row);

            int pkid = Integer.parseInt(model.getValueAt(row, 0).toString());
            //model.removeRow(row);

            System.err.println(pkid + " is selected : " + row);
            Date date = studentController.readStudentById(pkid).map(t -> t.getStuRegistrationDate()).get();
            Calendar c = Calendar.getInstance();
           
            c.setTime(date);
            c.add(Calendar.YEAR, 1);
            JOptionPane.showMessageDialog(this, c.getTime().toString(), " Next renewal date ", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnRenewal1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddStu;
    private javax.swing.JButton btnClearStu;
    private javax.swing.JButton btnDeleteStu;
    private java.awt.Button btnRenewal1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbStudents;
    private javax.swing.JTextField txtStudentAge;
    private javax.swing.JTextField txtStudentDate;
    private javax.swing.JTextField txtStudentID;
    private javax.swing.JTextField txtStudentName;
    private javax.swing.JTextField txtStudentParentContact;
    private javax.swing.JTextField txtStudentParentName;
    // End of variables declaration//GEN-END:variables





}
