/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.csye6200;

import edu.neu.csye6200.controller.ControllerStudent;
import edu.neu.csye6200.controller.ControllerTeacher;
import edu.neu.csye6200.controller.VaccineController;
import edu.neu.csye6200.model.ClassroomClass;
import edu.neu.csye6200.model.TeacherClass;
import edu.neu.csye6200.service.classroomFactory;

import java.util.List;
import javax.annotation.PostConstruct;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;


@Component
public class TeachersjPanel extends javax.swing.JPanel {

    /**
     * Creates new form StudentsjPanel
     */
    
    @Autowired
    ControllerTeacher teachController;
    @Autowired
    ControllerStudent studentController;
    @Autowired
    VaccineController vaccineController;
    @Autowired
    classroomFactory clsroomFactory;
    
    public TeachersjPanel() {
        initComponents();
    }

    @PostConstruct
    public void init() {
        try {
            populateBodyTeacher();
        } catch (Exception c) {
            c.printStackTrace();
            System.out.println("Something Went Wrong!");
        }
    }

    private void populateBodyTeacher() {
       // teachController.removeTeachers();
        List<TeacherClass> teachers = teachController.getAllTeachers();

        if (teachers.size() == 0) {
            teachController.addTestData();

            // Add teachers to classroom
            List<TeacherClass> newTeachers = teachController.getAllTeachers();
            addTs(newTeachers);

        } else {
            addTs(teachers);
            DefaultTableModel model = (DefaultTableModel) tableTeachers.getModel();

            if (model.getRowCount() == 0) {
                teachers.forEach(t -> {
                    model.addRow(new Object[]{t.getPersonId(), t.getPersonName(), t.getPersonAge(), t.getCredits()});
                });
            }
        }
    }

    private void addTs(List<TeacherClass> newTeachers) {
        List<ClassroomClass> allClassRooms = clsroomFactory.readAllClassRooms();
        ClassroomClass fc = allClassRooms.get(0);
        if (fc.getTeacherIdList().size() == 0) {
            int counter = 0;
            try {
                for (ClassroomClass clsroom : allClassRooms) {
                    int tempCounter = 0;
                    while (tempCounter < clsroom.getMaxGroups()) {
                        clsroom.addTeacherId(newTeachers.get(counter + tempCounter).getPersonId());
                        tempCounter++;
                    }
                    counter += tempCounter;
                }
            } catch (Exception ex) {
                System.out.println("****** Not Enough Teachers. Please Add at least 16 teachers ****");
                System.exit(1);
            }
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtTID = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnAddTeacher = new javax.swing.JButton();
        btnClearTeacher = new javax.swing.JButton();
        txtTAge = new javax.swing.JTextField();
        txtTCredits = new javax.swing.JTextField();
        btnDeleteTeacher = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableTeachers = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 102, 102));
        setPreferredSize(new java.awt.Dimension(800, 720));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Teacher", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel4.setForeground(java.awt.Color.gray);
        jPanel4.setOpaque(false);

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Teacher Id:");

        txtTID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTID.setToolTipText("");
        txtTID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTIDActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Name");

        txtTName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTName.setToolTipText("");
        txtTName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTNameActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Age");

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Ratings");

        btnAddTeacher.setBackground(new java.awt.Color(204, 255, 204));
        btnAddTeacher.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAddTeacher.setForeground(new java.awt.Color(51, 51, 51));
        btnAddTeacher.setText("Add Teacher");
        btnAddTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTeacherActionPerformed(evt);
            }
        });

        btnClearTeacher.setBackground(new java.awt.Color(204, 255, 204));
        btnClearTeacher.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnClearTeacher.setForeground(new java.awt.Color(51, 51, 51));
        btnClearTeacher.setText("Clear");
        btnClearTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearTeacherActionPerformed(evt);
            }
        });

        txtTAge.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTAge.setToolTipText("");
        txtTAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTAgeActionPerformed(evt);
            }
        });

        txtTCredits.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTCredits.setToolTipText("");
        txtTCredits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTCreditsActionPerformed(evt);
            }
        });

        btnDeleteTeacher.setBackground(new java.awt.Color(204, 255, 204));
        btnDeleteTeacher.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnDeleteTeacher.setText("Delete");
        btnDeleteTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteTeacherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(612, 612, 612))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(btnAddTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(btnClearTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(btnDeleteTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTAge, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTID)
                    .addComponent(txtTCredits)
                    .addComponent(txtTName, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(119, 119, 119))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(txtTAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtTCredits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnAddTeacher, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(btnClearTeacher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDeleteTeacher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teach1.jpeg"))); // NOI18N

        tableTeachers.setBackground(new java.awt.Color(237, 237, 237));
        tableTeachers.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tableTeachers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Teacher_Id", "Teacher_Name", "Teacher_Age", "Credits"
            }
        ));
        jScrollPane2.setViewportView(tableTeachers);
        if (tableTeachers.getColumnModel().getColumnCount() > 0) {
            tableTeachers.getColumnModel().getColumn(0).setResizable(false);
            tableTeachers.getColumnModel().getColumn(1).setResizable(false);
            tableTeachers.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane2)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(191, 191, 191))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTIDActionPerformed

    private void txtTNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTNameActionPerformed

    private void txtTAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTAgeActionPerformed

    private void txtTCreditsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTCreditsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTCreditsActionPerformed

    private void btnAddTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTeacherActionPerformed
        // TODO add your handling code here:

        String id = txtTID.getText();
        String age = txtTAge.getText();
        String name = txtTName.getText();
        String credit = txtTCredits.getText();

        if (id.isEmpty() || age.isEmpty() || name.isEmpty() || credit.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter All Fields", "Try Again", JOptionPane.ERROR_MESSAGE);
        } else {
            DefaultTableModel model = (DefaultTableModel) tableTeachers.getModel();
            model.addRow(new Object[]{id, name, age, credit});
        }

        txtTID.setText("");
        txtTAge.setText("");
        txtTName.setText("");
        txtTCredits.setText("");

        // add to bin file
        // TODO add your handling code here:
//       DefaultTableModel model = (DefaultTableModel) tableTeachers.getModel();
//        Vector<Vector> tableData = model.getDataVector();
//        
//        // Saving the Object in a File
//        try{
//            FileOutputStream fos = 
//                    new FileOutputStream("D:\\code\\swing\\Final\\OOD_Final_Project_Daycare\\DayCare\\src\\com\\ood\\ui\\teachers.bin");
//            ObjectOutputStream oos = new ObjectOutputStream(fos);
//            
//            oos.writeObject(tableData);
//            oos.close();
//            fos.close();
//        } catch (Exception ex){
//            ex.printStackTrace();
//        }
        //push to db
        String csv = id + "," + name + "," + age + "," + credit;
        System.err.println(csv + "is added to teache db");
        teachController.addTeacher(csv);
        // Adding teacher to last classroom
        clsroomFactory.readAllClassRooms().get(clsroomFactory.readAllClassRooms().size()-1).addTeacherId(Integer.parseInt(id));
    }//GEN-LAST:event_btnAddTeacherActionPerformed

    private void btnClearTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearTeacherActionPerformed
        // TODO add your handling code here:
        txtTID.setText("");
        txtTAge.setText("");
        txtTName.setText("");
        txtTCredits.setText("");
    }//GEN-LAST:event_btnClearTeacherActionPerformed

    private void btnDeleteTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteTeacherActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        int row = tableTeachers.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "No Row is Selected", "Please Select Row", JOptionPane.ERROR_MESSAGE);
        } else {
            //int pkid = (int)tableTeachers.getModel().getValueAt(row, 0);
            DefaultTableModel model = (DefaultTableModel) tableTeachers.getModel();
            //            String k = model.getValueAt(0, 0).toString();
            //            System.err.println(k + " is about to deleted : " + row);

            int pkid = Integer.parseInt(model.getValueAt(row, 0).toString());
            model.removeRow(row);

            System.err.println(pkid + " is deleted : " + row);
            //int age = teachController.getTeacherById(pkid).get().getAge();

            teachController.removeTeacherById(pkid);

            //            ClassroomClass classRoom = classroomFactory.getClassRoom(age);
            //            classRoom.removeStudentId(pkid);
        }
    }//GEN-LAST:event_btnDeleteTeacherActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTeacher;
    private javax.swing.JButton btnClearTeacher;
    private javax.swing.JButton btnDeleteTeacher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableTeachers;
    private javax.swing.JTextField txtTAge;
    private javax.swing.JTextField txtTCredits;
    private javax.swing.JTextField txtTID;
    private javax.swing.JTextField txtTName;
    // End of variables declaration//GEN-END:variables
}
