/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.csye6200;

import edu.neu.csye6200.controller.ControllerStudent;
import edu.neu.csye6200.controller.ControllerTeacher;
import edu.neu.csye6200.controller.VaccineController;
import edu.neu.csye6200.model.ImmunizationClass;
import edu.neu.csye6200.service.classroomFactory;
import java.util.Calendar;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;


@Component
public class ImmunizationsjPanel extends javax.swing.JPanel {

    /**
     * Creates new form StudentsjPanel
     */

    @Autowired
    ControllerTeacher teachController;
    @Autowired
    ControllerStudent studentController;
    @Autowired
    VaccineController vaccineController;
    @Autowired
    classroomFactory clsroomFactory;

    public ImmunizationsjPanel() {
        initComponents();
    }

    @PostConstruct
    public void init() {
        try {
            this.populateBodyVaccinations();
        } catch (Exception c) {
            c.printStackTrace();
            System.out.println("Something went wrong!");
        }
    }

    public void populateBodyVaccinations() {
       // vaccineController.removeAll();
        List<ImmunizationClass> vaccinations = vaccineController.getAllVaccines();

        if (vaccinations.size()<=1&&vaccinations.get(0).getVaccine1Dose1()==null) {
            vaccinations.remove(0);
            vaccineController.addTestData();
        } else {
            DefaultTableModel model = (DefaultTableModel) tbVaccine.getModel();

            if (model.getRowCount() == 0) {
                vaccinations.forEach(t -> {
                    model.addRow(new Object[]{t.getPersonID(), t.readVaccine(), t.getVaccine1Dose1(), t.getVaccine1Dose2(), t.readVaccine2(), t.getVaccine2Dose1()});
                });
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtPersonId = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtV1Dose1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtV2Dose1 = new javax.swing.JTextField();
        btnAddRecord = new javax.swing.JButton();
        btnClearRecord = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        txtVaccine2 = new javax.swing.JTextField();
        txtVaccine1 = new javax.swing.JTextField();
        txtV1Dose2 = new javax.swing.JTextField();
        btnDeleteRecord = new javax.swing.JButton();
        btnRenewal = new java.awt.Button();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbVaccine = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 102));
        setPreferredSize(new java.awt.Dimension(1000, 800));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Immunization Record", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.setOpaque(false);

        jLabel16.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("ID");

        txtPersonId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPersonId.setToolTipText("");
        txtPersonId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPersonIdActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Vaccine 1");

        jLabel18.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Dose 1");

        txtV1Dose1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtV1Dose1.setToolTipText("");
        txtV1Dose1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtV1Dose1ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Dose 2");

        jLabel20.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Vaccine 2");

        txtV2Dose1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtV2Dose1.setToolTipText("");
        txtV2Dose1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtV2Dose1ActionPerformed(evt);
            }
        });

        btnAddRecord.setBackground(new java.awt.Color(204, 255, 204));
        btnAddRecord.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAddRecord.setText("Add Record");
        btnAddRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRecordActionPerformed(evt);
            }
        });

        btnClearRecord.setBackground(new java.awt.Color(204, 255, 204));
        btnClearRecord.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnClearRecord.setText("Clear");
        btnClearRecord.setPreferredSize(new java.awt.Dimension(89, 29));
        btnClearRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearRecordActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Dose 1");

        txtVaccine2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtVaccine2.setToolTipText("");
        txtVaccine2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVaccine2ActionPerformed(evt);
            }
        });

        txtVaccine1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtVaccine1.setToolTipText("");
        txtVaccine1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVaccine1ActionPerformed(evt);
            }
        });

        txtV1Dose2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtV1Dose2.setToolTipText("");
        txtV1Dose2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtV1Dose2ActionPerformed(evt);
            }
        });

        btnDeleteRecord.setBackground(new java.awt.Color(204, 255, 204));
        btnDeleteRecord.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnDeleteRecord.setText("Delete");
        btnDeleteRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteRecordActionPerformed(evt);
            }
        });

        btnRenewal.setBackground(new java.awt.Color(102, 204, 0));
        btnRenewal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnRenewal.setForeground(new java.awt.Color(0, 0, 0));
        btnRenewal.setLabel("Alert");
        btnRenewal.setPreferredSize(new java.awt.Dimension(89, 29));
        btnRenewal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRenewalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtVaccine2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtVaccine1)
                                .addComponent(txtV1Dose1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtV1Dose2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtPersonId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtV2Dose1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(btnAddRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClearRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(btnRenewal, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPersonId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtVaccine1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtV1Dose1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtV1Dose2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVaccine2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtV2Dose1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAddRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDeleteRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnClearRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnRenewal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 27, Short.MAX_VALUE))
        );

        tbVaccine.setBackground(new java.awt.Color(236, 235, 235));
        tbVaccine.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tbVaccine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student_ID", "Vaccine 1", "Dose 1", "Dose 2", "Vaccine 2", "Dose 1"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbVaccine.setGridColor(new java.awt.Color(153, 204, 255));
        tbVaccine.setSelectionBackground(new java.awt.Color(153, 204, 255));
        tbVaccine.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane3.setViewportView(tbVaccine);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vacc3.jpeg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(298, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPersonIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPersonIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPersonIdActionPerformed

    private void txtVaccine1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVaccine1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVaccine1ActionPerformed

    private void txtV1Dose1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtV1Dose1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtV1Dose1ActionPerformed

    private void txtV1Dose2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtV1Dose2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtV1Dose2ActionPerformed

    private void txtV2Dose1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtV2Dose1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtV2Dose1ActionPerformed

    private void btnAddRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRecordActionPerformed
        // TODO add your handling code here:
        String id = txtPersonId.getText();
        String vaccine1 = txtVaccine1.getText();
        String v1t1 = txtV1Dose1.getText();
        String v1t2 = txtV1Dose2.getText();
        String vaccine2 = txtVaccine2.getText();
        String v2t1 = txtV2Dose1.getText();

        if (id.isEmpty() || vaccine1.isEmpty() || v1t1.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Atleast 1 vaccination info", "Try Again", JOptionPane.ERROR_MESSAGE);
        } else {
            DefaultTableModel model = (DefaultTableModel) tbVaccine.getModel();
            model.addRow(new Object[]{id, vaccine1, v1t1, v1t2, vaccine2, v2t1});
        }

        txtPersonId.setText("");
        txtVaccine1.setText("");
        txtV1Dose1.setText("");
        txtV1Dose2.setText("");
        txtVaccine2.setText("");
        txtV2Dose1.setText("");

        String csv = id + "," + vaccine1 + "," + v1t1 + "," + v1t2 + "," + vaccine2 + "," + v2t1;
        System.err.println(csv + "is added to vaccine db");

        vaccineController.addVaccine(csv);
    }//GEN-LAST:event_btnAddRecordActionPerformed

    private void btnClearRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearRecordActionPerformed
        // TODO add your handling code here:
        txtPersonId.setText("");
        txtVaccine1.setText("");
        txtV1Dose1.setText("");
        txtV1Dose2.setText("");
        txtVaccine2.setText("");
        txtV2Dose1.setText("");
    }//GEN-LAST:event_btnClearRecordActionPerformed

    private void txtVaccine2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVaccine2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVaccine2ActionPerformed

    private void btnDeleteRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteRecordActionPerformed
        // TODO add your handling code here:
        int row = tbVaccine.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "No Row is Selected", "Please Select Row", JOptionPane.ERROR_MESSAGE);
        } else {
            //int pkid = (int)tableTeachers.getModel().getValueAt(row, 0);
            DefaultTableModel model = (DefaultTableModel) tbVaccine.getModel();
            //            String k = model.getValueAt(0, 0).toString();
            //            System.err.println(k + " is about to deleted : " + row);

            int pkid = Integer.parseInt(model.getValueAt(row, 0).toString());
            model.removeRow(row);

            System.err.println(pkid + " is deleted : " + row);
            vaccineController.removeVaccineById(pkid);

        }
    }//GEN-LAST:event_btnDeleteRecordActionPerformed

    private void btnRenewalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRenewalActionPerformed
        // TODO add your handling code here:
        int row = tbVaccine.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "No Row is Selected", "Please Select Row", JOptionPane.ERROR_MESSAGE);
        } else {
            //int pkid = (int)tableTeachers.getModel().getValueAt(row, 0);
            DefaultTableModel model = (DefaultTableModel) tbVaccine.getModel();
            //            String k = model.getValueAt(0, 0).toString();
            //            System.err.println(k + " is about to deleted : " + row);

            int pkid = Integer.parseInt(model.getValueAt(row, 0).toString());
            //model.removeRow(row);

            System.err.println(pkid + " is selected : " + row);
            ImmunizationClass vaccination = vaccineController.getVaccinesById(pkid).get();
            if (vaccination.readVaccine() == null && vaccination.readVaccine2() == null) {
                JOptionPane.showMessageDialog(this, "Student is to be vaccinated", "Vaccination alert", JOptionPane.ERROR_MESSAGE);
            } else if (vaccination.getVaccine1Dose2() == null) {
                Calendar c = Calendar.getInstance();
                c.setTime(vaccination.getVaccine1Dose1());
                c.add(Calendar.MONTH, 3);
                JOptionPane.showMessageDialog(this, c.getTime().toString(), " Next Immunization date(Dose 2)", JOptionPane.ERROR_MESSAGE);
                //JOptionPane.showMessageDialog(this, "Student is to be vaccinated", "Vaccine1 dose 2 missing alert", JOptionPane.ERROR_MESSAGE);
            } else if (vaccination.readVaccine2() == null) {
                Calendar c = Calendar.getInstance();
                c.setTime(vaccination.getVaccine1Dose1());
                c.add(Calendar.YEAR, 1);
                JOptionPane.showMessageDialog(this, c.getTime().toString(), " Next Immunization date(Vaccine 2)", JOptionPane.ERROR_MESSAGE);
                //JOptionPane.showMessageDialog(this, "Student is to be vaccinated", "Vaccine2 missing alert", JOptionPane.ERROR_MESSAGE);
            }
                   
        }
    }//GEN-LAST:event_btnRenewalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRecord;
    private javax.swing.JButton btnClearRecord;
    private javax.swing.JButton btnDeleteRecord;
    private java.awt.Button btnRenewal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbVaccine;
    private javax.swing.JTextField txtPersonId;
    private javax.swing.JTextField txtV1Dose1;
    private javax.swing.JTextField txtV1Dose2;
    private javax.swing.JTextField txtV2Dose1;
    private javax.swing.JTextField txtVaccine1;
    private javax.swing.JTextField txtVaccine2;
    // End of variables declaration//GEN-END:variables
}
